### ISSUE TITLE
Images won't mount after upgrading Ubuntu from 15.x to 16.04

### ISSUE THREAD

**Issue by anseljh** [ralphje/imagemounter#7] opened 2016-07-12 17:33 UTC
Hello, I have a strange an unexpected error after upgrading my Ubuntu virtual machine to the latest version, 16.04. I'm not sure what could be the problem. I'll install an older version of Ubuntu to overcome the problem in the short term, but I thought I should report the error here.

Commands saved in a bash script that worked previously now give this error:
`[-] invalid literal for int() with base 10: '-------'`

Here is the full output using `-vvvv`:

![2016-07-12-imount](https://cloud.githubusercontent.com/assets/2075772/16776744/a73eed90-481b-11e6-967f-c4e65a39ffba.png)

**Comment by ralphje** [comment] 2016-07-12 18:06
Thanks for the report.

This is caused by a change in mmls output. It has been resolved in master and 3.0.0a1. Could you try to install the GitHub version?

**Closed by ralphje** 2016-07-12 18:06 UTC

**Comment by anseljh** [comment] 2016-07-12 18:15
Yes, the GitHub version works. Thank you!
